---
- name: Install and configure Nginx with IP restriction
  hosts: my_hosts
  become: true
  gather_facts: true

  vars:
    allowed_ips:
      - 192.168.1.50
      - 192.168.1.60
      - 192.168.1.70

  roles:
    - nginx
