---
- name: "Install the common packages"
  become: true
  hosts: all
  gather_facts: true
  roles:
    - common

- name: Install the web server
  become: true
  hosts: webservers
  gather_facts: false
  roles:
    - webserver

- name: Install and configure the database
  gather_facts: true
  become: true
  hosts: dbservers
  roles:
    - dbserver