#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/webserver
- name: Install Node.js and NPM
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm
    state: present

- name: Create the application directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ users.0.name }}"
    group: "{{ users.0.group }}"
    mode: '0755'

- name: Install NPM packages
  ansible.builtin.npm:
    name: "{{ item }}"
    global: true
  loop: "{{ npm_packages }}"

- name: Initialize a new React project
  ansible.builtin.command:
    cmd: "npx create-react-app {{ app_name}}"
    chdir: "{{ app_dir }}"
  args:
    creates: "{{ app_dir }}/{{ app_name }}"

- name: Configure React development server to listen on 0.0.0.0
  ansible.builtin.lineinfile:
    path: "{{ app_dir }}/{{ app_name }}/.env"
    line: "HOST=0.0.0.0"
    create: true

- name: Deploy custom App.css
  ansible.builtin.copy:
    src: App.css
    dest: "{{ app_dir }}/{{ app_name }}/src/App.css"
    mode: '0644'
  when: deploy_custom_page

- name: Deploy custom App.css
  ansible.builtin.template:
    src: App.js.j2
    dest: "{{ app_dir }}/{{ app_name }}/src/App.js"
    mode: '0644'
    variable_start_string: "{[%"
    variable_end_string: "%]}"
  when: deploy_custom_page

- name: Start the developement server (React)
  ansible.builtin.command:
    cmd: pm2 start npm -- start --watch
    chdir: "{{ app_dir }}/{{ app_name }}"
